name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Sanity test
        run: python -c "from flask import Flask; print('Flask OK')"
      - name: Save result
        run: echo ok > result.txt
      - uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: result.txt

  use-other-repo:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          repository: yourusername/other-project
          path: other
      - uses: actions/download-artifact@v4
        with:
          name: build-result
      - run: |
          echo "Artifact content:"
          cat result.txt
          echo "Files in other project:"
          ls other/
